name: ðŸš€ Build & Release Plexboxd

on:
  push:
    branches:
      - main
      - master
    tags-ignore:
      - 'v*'
  workflow_dispatch:
    inputs:
      release_version:
        description: "Manual release version (e.g. v1.2.3)"
        required: false
        default: ""

permissions:
  contents: write
  packages: write

env:
  IMAGE_NAME: nate8727/plexboxd
  PYTHON_VERSION: "3.12"

jobs:
  build-and-push:
    name: ðŸ³ Build & Push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from inputs or generate date tag
        id: version
        run: |
          if [ -n "${{ github.event.inputs.release_version }}" ]; then
            echo "version=${{ github.event.inputs.release_version }}" >> $GITHUB_OUTPUT
          else
            echo "version=v$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT
          fi
          echo "Release version: ${{ steps.version.outputs.version }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}
          build-args: |
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}

      - name: Generate changelog
        id: changelog
        run: |
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          git log -1 --pretty=format:"%s%n%n%b" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Git tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }}

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: "Plexboxd ${{ steps.version.outputs.version }}"
          body: |
            ðŸ§© **Plexboxd Release** ${{ steps.version.outputs.version }}

            - Docker image: `${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}`
            - Build date: $(date -u)
            - Commit: ${{ github.sha }}

            **Changes:**
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
