import { create } from "@storybook/theming";

export const spokenarrLight = create({
  base: "light",
  brandTitle: "Spokenarr UI",
  brandUrl: "https://spokenarr.io",
  brandImage: "/logos/spokenarr-logo.svg",
  colorPrimary: "#6C63FF",
  colorSecondary: "#FF6584",
  appBg: "linear-gradient(180deg, #f9f9ff 0%, #eef0ff 100%)",
  appContentBg: "#ffffff",
  appBorderColor: "#d1d5db",
  appBorderRadius: 12,
  textColor: "#1f2937",
  textInverseColor: "#ffffff",
  barTextColor: "#1f2937",
  barSelectedColor: "#6C63FF",
  barBg: "#ffffff",
  inputBg: "#ffffff",
  inputBorder: "#d1d5db",
  inputTextColor: "#111827",
  inputBorderRadius: 8,
});

export const spokenarrDark = create({
  base: "dark",
  brandTitle: "Spokenarr UI",
  brandUrl: "https://spokenarr.io",
  brandImage: "/logos/spokenarr-logo.svg",
  colorPrimary: "#A78BFA",
  colorSecondary: "#FF7AB8",
  appBg: "linear-gradient(180deg, #0f0f2d 0%, #1a1446 100%)",
  appContentBg: "#1E1B4B",
  appBorderColor: "#312E81",
  appBorderRadius: 12,
  textColor: "#E0E7FF",
  textInverseColor: "#111827",
  barTextColor: "#E0E7FF",
  barSelectedColor: "#A78BFA",
  barBg: "#1E1B4B",
  inputBg: "#312E81",
  inputBorder: "#4338CA",
  inputTextColor: "#F9FAFB",
  inputBorderRadius: 8,
});
